/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import classes.Dados;

/**
 *
 * @author Melges
 */
public class frmPrincipal extends javax.swing.JFrame {
        
    private Dados msDados;
     
    public void setDados(Dados msDados) {
        this.msDados = msDados;
    }
    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPaneFrmPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuArquivoClientes = new javax.swing.JMenuItem();
        menuArquivoPersonas = new javax.swing.JMenuItem();
        menuArquivoUsuarios = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuArquivoTrocarSenha = new javax.swing.JMenuItem();
        menuArquivoTrocarUsuario = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuArquivoSair = new javax.swing.JMenuItem();
        menuMovimentos = new javax.swing.JMenu();
        menuMovimentosNovaAcao = new javax.swing.JMenuItem();
        menuMovimentosRelatorio = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        menuAjudaSobre = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PAINEL PERSONAS");

        desktopPaneFrmPrincipal.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout desktopPaneFrmPrincipalLayout = new javax.swing.GroupLayout(desktopPaneFrmPrincipal);
        desktopPaneFrmPrincipal.setLayout(desktopPaneFrmPrincipalLayout);
        desktopPaneFrmPrincipalLayout.setHorizontalGroup(
            desktopPaneFrmPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1006, Short.MAX_VALUE)
        );
        desktopPaneFrmPrincipalLayout.setVerticalGroup(
            desktopPaneFrmPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        menuArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-banco-de-dados-50.png"))); // NOI18N
        menuArquivo.setText("Arquivo");

        menuArquivoClientes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuArquivoClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-clientes-30.png"))); // NOI18N
        menuArquivoClientes.setText("Clientes");
        menuArquivoClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArquivoClientesActionPerformed(evt);
            }
        });
        menuArquivo.add(menuArquivoClientes);

        menuArquivoPersonas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuArquivoPersonas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-clientes-30.png"))); // NOI18N
        menuArquivoPersonas.setText("Personas");
        menuArquivo.add(menuArquivoPersonas);

        menuArquivoUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuArquivoUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-clientes-30.png"))); // NOI18N
        menuArquivoUsuarios.setText("Usuarios");
        menuArquivoUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArquivoUsuariosActionPerformed(evt);
            }
        });
        menuArquivo.add(menuArquivoUsuarios);
        menuArquivo.add(jSeparator1);

        menuArquivoTrocarSenha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuArquivoTrocarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-senha-50.png"))); // NOI18N
        menuArquivoTrocarSenha.setText("Trocar Senha");
        menuArquivo.add(menuArquivoTrocarSenha);

        menuArquivoTrocarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuArquivoTrocarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-senha-50.png"))); // NOI18N
        menuArquivoTrocarUsuario.setText("TrocarUsuario");
        menuArquivo.add(menuArquivoTrocarUsuario);
        menuArquivo.add(jSeparator2);

        menuArquivoSair.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuArquivoSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-sair-50.png"))); // NOI18N
        menuArquivoSair.setText("Sair");
        menuArquivo.add(menuArquivoSair);

        jMenuBar1.add(menuArquivo);

        menuMovimentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-ação-64.png"))); // NOI18N
        menuMovimentos.setText("Movimentos");

        menuMovimentosNovaAcao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuMovimentosNovaAcao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-ação-50.png"))); // NOI18N
        menuMovimentosNovaAcao.setText("Nova Ação");
        menuMovimentosNovaAcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMovimentosNovaAcaoActionPerformed(evt);
            }
        });
        menuMovimentos.add(menuMovimentosNovaAcao);

        menuMovimentosRelatorio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuMovimentosRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-papel-50.png"))); // NOI18N
        menuMovimentosRelatorio.setText("Relatório de Ações");
        menuMovimentos.add(menuMovimentosRelatorio);

        jMenuBar1.add(menuMovimentos);

        menuAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-ajuda-50.png"))); // NOI18N
        menuAjuda.setText("Ajuda");

        menuAjudaSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-sobre-50.png"))); // NOI18N
        menuAjudaSobre.setText("Sobre");
        menuAjuda.add(menuAjudaSobre);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-ajuda-50 (1).png"))); // NOI18N
        jMenuItem1.setText("Ajuda");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuAjuda.add(jMenuItem1);

        jMenuBar1.add(menuAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPaneFrmPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPaneFrmPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuMovimentosNovaAcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMovimentosNovaAcaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuMovimentosNovaAcaoActionPerformed

    private void menuArquivoClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArquivoClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuArquivoClientesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuArquivoUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArquivoUsuariosActionPerformed
        frmUsuarios formularioUsuario = new frmUsuarios();
        desktopPaneFrmPrincipal.add(formularioUsuario);
        formularioUsuario.show();
        
    }//GEN-LAST:event_menuArquivoUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPaneFrmPrincipal;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenuItem menuAjudaSobre;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuItem menuArquivoClientes;
    private javax.swing.JMenuItem menuArquivoPersonas;
    private javax.swing.JMenuItem menuArquivoSair;
    private javax.swing.JMenuItem menuArquivoTrocarSenha;
    private javax.swing.JMenuItem menuArquivoTrocarUsuario;
    private javax.swing.JMenuItem menuArquivoUsuarios;
    private javax.swing.JMenu menuMovimentos;
    private javax.swing.JMenuItem menuMovimentosNovaAcao;
    private javax.swing.JMenuItem menuMovimentosRelatorio;
    // End of variables declaration//GEN-END:variables
}
